#!/usr/bin/env node
/**
 * Generate schema.generated.ts from schema.sql
 * 
 * This script reads the schema.sql file and generates a TypeScript file
 * with the SQL content as a constant. This allows the SQL file to be the
 * source of truth while avoiding runtime file reading in bundled code.
 */

const fs = require('fs');
const path = require('path');

const schemaPath = path.join(__dirname, '../action/src/db/schema.sql');
const outputPath = path.join(__dirname, '../action/src/db/schema.generated.ts');

try {
  // Read the SQL schema file
  if (!fs.existsSync(schemaPath)) {
    console.error(`Error: Schema file not found at ${schemaPath}`);
    process.exit(1);
  }

  const schemaSql = fs.readFileSync(schemaPath, 'utf-8');

  // Generate TypeScript file content
  const output = `/**
 * Generated from schema.sql
 * DO NOT EDIT - This file is auto-generated by scripts/generate-schema.cjs
 */

export const SCHEMA_SQL_TEMPLATE = ${JSON.stringify(schemaSql)};
`;

  // Ensure output directory exists
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    console.error(`Error: Output directory does not exist at ${outputDir}`);
    process.exit(1);
  }

  // Write the generated TypeScript file
  fs.writeFileSync(outputPath, output, 'utf-8');
  console.log('✓ Generated schema.generated.ts from schema.sql');
} catch (error) {
  console.error(`Error generating schema: ${error.message}`);
  process.exit(1);
}
